# Generated by Django 6.0.1 on 2026-04-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_agence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='etage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='localisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_chambres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_cuisines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_salles_bain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_salons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bien',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('vendu', 'Vendu'), ('reserve', 'Réservé')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='bien',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('commerce', 'Commerce')], default='appartement', max_length=30),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('registre_commerce', 'Registre de Commerce'), ('acte_propriete', 'Acte de Propriété'), ('contrat_location', 'Contrat de Location'), ('autre', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_agence', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biens.bien')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
