# Generated by Django 6.0.3 on 2026-04-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_bien_agence_bien_ascenseur_bien_balcon_bien_etage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commentaires_verification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
