# Generated by Django 6.0.3 on 2026-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_document_commentaires_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('registre_commerce', 'Registre de Commerce'), ('acte_propriete', 'Acte de Propriété'), ('contrat_location', 'Contrat de Location'), ('cni_recto', 'CNI / Passeport Recto'), ('cni_verso', 'CNI / Passeport Verso'), ('justif_propriete', 'Justificatif de Propriété'), ('selfie_cni', "Selfie avec pièce d'identité"), ('facture_cie', 'Facture CIE / SODECI'), ('rccm_doc', 'Registre de commerce (RCCM)'), ('ncc_doc', 'Numéro Contribuable (NCC)'), ('cni_responsable', 'Pièce du responsable'), ('autorisation', "Autorisation d'exercer"), ('logo_agence', "Logo de l'agence"), ('autre', 'Autre')], max_length=50),
        ),
    ]
