# Generated by Django 6.0.1 on 2026-06-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_alter_document_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='meuble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='proximite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bien',
            name='securite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='transaction_type',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente'), ('location_vente', 'Location / Vente')], default='location', max_length=20),
        ),
    ]
