# Generated by Django 6.0.3 on 2026-07-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_bien_latitude_bien_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='adresse_precise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bien',
            name='annee_construction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='caution_mois',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='charges_comprises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='climatisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='commune',
            field=models.CharField(blank=True, choices=[('cocody', 'Cocody'), ('yopougon', 'Yopougon'), ('marcory', 'Marcory'), ('bingerville', 'Bingerville'), ('plateau', 'Plateau'), ('adjame', 'Adjame'), ('treichville', 'Treichville'), ('koumassi', 'Koumassi'), ('angre', 'Angré'), ('riviera', 'Riviera')], max_length=30),
        ),
        migrations.AddField(
            model_name='bien',
            name='cuisine_equipee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='disponible_a_partir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='escalier_interieur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='gardiennage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='groupe_electrogene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='interphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_niveaux',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='nombre_pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bien',
            name='parking_garde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='pays',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
        migrations.AddField(
            model_name='bien',
            name='prix_negociable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bien',
            name='securite_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='terrasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='titre_propriete',
            field=models.CharField(blank=True, choices=[('acd', 'ACD'), ('titre_foncier', 'Titre Foncier (TF)'), ('lettre_attribution', "Lettre d'attribution"), ('autre_en_cours', 'Autre/En cours')], max_length=30),
        ),
        migrations.AddField(
            model_name='bien',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('loue', 'Loué'), ('vendu', 'Vendu')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(choices=[('appartement', 'Appartement'), ('duplex', 'Duplex'), ('villa', 'Villa'), ('maison', 'Maison'), ('bureau', 'Bureau'), ('terrain', 'Terrain'), ('studio', 'Studio'), ('commerce', 'Commerce')], default='appartement', max_length=30),
        ),
        migrations.AlterField(
            model_name='bien',
            name='ville',
            field=models.CharField(default='Abidjan', max_length=100),
        ),
    ]
