# Generated by Django 6.0.3 on 2026-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0007_bien_adresse_precise_bien_annee_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='est_suspect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='raisons_suspicion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bien',
            name='score_suspicion',
            field=models.FloatField(default=0),
        ),
    ]
