# Generated by Django 6.0.3 on 2026-07-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0008_bien_est_suspect_bien_raisons_suspicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='eau_courante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='electricite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='travaux_a_prevoir',
            field=models.BooleanField(default=False),
        ),
    ]
