# Generated by Django 6.0.1 on 2026-04-07 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
        ('biens', '0002_bien_agence_bien_ascenseur_bien_balcon_bien_etage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('utilisateur', 'bien')},
        ),
    ]
