# Generated by Django 6.0.1 on 2026-04-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='compte_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire'), ('agence', 'Agence Immobilière'), ('admin', 'Administrateur')], default='locataire', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('date_expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField(blank=True)),
                ('numero_registre_commerce', models.CharField(blank=True, max_length=100)),
                ('numero_contribuable', models.CharField(blank=True, max_length=100)),
                ('document_legal', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_creation_agence', models.DateField(blank=True, null=True)),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('nombre_biens', models.PositiveIntegerField(default=0)),
                ('type_biens', models.CharField(blank=True, max_length=200)),
                ('zones_couvertes', models.TextField(blank=True)),
                ('nombre_agents', models.PositiveIntegerField(default=0)),
                ('responsable_agence', models.CharField(blank=True, max_length=100)),
                ('nombre_transactions', models.PositiveIntegerField(default=0)),
                ('revenu_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('compte_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField(blank=True)),
                ('type_piece', models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport')], max_length=20)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('photo_piece_recto', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('photo_piece_verso', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('selfie_verification', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('nombre_biens', models.PositiveIntegerField(default=0)),
                ('type_biens', models.CharField(blank=True, max_length=200)),
                ('zone_activite', models.CharField(blank=True, max_length=200)),
                ('nombre_locations', models.PositiveIntegerField(default=0)),
                ('revenu_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('compte_verifie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('arnaque', 'Arnaque'), ('faux_document', 'Faux Document'), ('comportement_inapproprie', 'Comportement Inapproprié'), ('bien_fictif', 'Bien Fictif'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
