# Generated by Django 6.0.3 on 2026-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_userprofile_compte_actif_userprofile_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilagence',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='signalement',
            name='notes_admin',
            field=models.TextField(blank=True),
        ),
    ]
