# Generated by Django 6.0.3 on 2026-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_profilagence_email_signalement_notes_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilproprietaire',
            name='type_proprietaire',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire'), ('agent', 'Agent Immobilier'), ('agence', 'Agence Immobilière'), ('admin', 'Administrateur')], default='locataire', max_length=20),
        ),
    ]
