# Generated by Django 6.0.1 on 2026-05-16 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_alter_document_type_document'),
        ('utilisateurs', '0004_profilproprietaire_type_proprietaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='cible',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='notes_admin',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='type_signalement',
        ),
        migrations.AddField(
            model_name='signalement',
            name='bien',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='biens.bien'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='raison',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere_recherche', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_recherches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte')], max_length=50)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], default='succes', max_length=20)),
                ('reference_transaction', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('abonnement', 'Abonnement'), ('reservation', 'Reservation')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='utilisateurs.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('heure_visite', models.TimeField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='biens.bien')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='utilisateurs.ville')),
            ],
            options={
                'unique_together': {('nom', 'ville')},
            },
        ),
    ]
