# Generated by Django 6.0.3 on 2026-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_ville_remove_signalement_cible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20),
        ),
    ]
