# Generated by Django 6.0.3 on 2026-07-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_paiement_date_maj_paiement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilagence',
            name='kyc_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilagence',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Non démarrée'), ('pending', 'En cours de vérification'), ('approved', 'Vérifiée'), ('declined', 'Refusée')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='profilagence',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilproprietaire',
            name='kyc_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilproprietaire',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Non démarrée'), ('pending', 'En cours de vérification'), ('approved', 'Vérifiée'), ('declined', 'Refusée')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='profilproprietaire',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
