# Generated by Django 6.0.3 on 2026-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fichier',
            field=models.ImageField(blank=True, null=True, upload_to='biens_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
