# Generated by Django 6.0.1 on 2026-04-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('type_bien', models.CharField(blank=True, max_length=50)),
                ('nombre_chambres_min', models.PositiveIntegerField(blank=True, null=True)),
                ('localisation', models.TextField(blank=True)),
                ('resultats', models.JSONField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('historique', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
