# Generated by Django 6.0.3 on 2026-04-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationia',
            name='analyse_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
