from django.urls import path

from .views import (
    ChangePasswordView,
    DeleteAccountView,
    LoginView,
    LogoutView,
    MeUpdateView,
    MeView,
    RegisterView,
    RefreshView,
    VerifyEmailView,
    ResendVerificationView,
    UserProfileView,
    ProfilProprietaireView,
    ProfilAgenceView,
    PasswordResetView,
    PasswordResetConfirmView,
    SignalementListCreateView,
    SignalementDetailView,
    AgentsListView,
    AgentDetailView,
    AgentBiensView,
    AgentAvisView,
    LaisserAvisAgentView,
    ProfilProprietaireVerificationView,
    ProfilAgenceVerificationView,
    UtilisateursView,
)

urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('auth/refresh/', RefreshView.as_view(), name='token_refresh'),
    path('auth/verify-email/', VerifyEmailView.as_view(), name='verify_email'),
    path('auth/resend-verification/', ResendVerificationView.as_view(), name='resend_verification'),
    path('utilisateurs/me/', MeView.as_view(), name='me'),
    path('utilisateurs/me/update/', MeUpdateView.as_view(), name='me_update'),
    path('utilisateurs/', UtilisateursView.as_view(), name='utilisateurs'),
    path('utilisateurs/profile/', UserProfileView.as_view(), name='user_profile'),
    path('utilisateurs/profil-proprietaire/', ProfilProprietaireView.as_view(), name='profil_proprietaire'),
    path('utilisateurs/profil-proprietaire/verifier/', ProfilProprietaireVerificationView.as_view(), name='profil_proprietaire_verifier'),
    path('utilisateurs/profil-agence/', ProfilAgenceView.as_view(), name='profil_agence'),
    path('utilisateurs/profil-agence/verifier/', ProfilAgenceVerificationView.as_view(), name='profil_agence_verifier'),
    path('utilisateurs/password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('utilisateurs/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('utilisateurs/signalements/', SignalementListCreateView.as_view(), name='signalements_list'),
    path('utilisateurs/signalements/<int:pk>/', SignalementDetailView.as_view(), name='signalement_detail'),
    path('utilisateurs/delete/', DeleteAccountView.as_view(), name='user_delete'),
    path('agents/', AgentsListView.as_view(), name='agents_list'),
    path('agents/<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('agents/<int:pk>/biens/', AgentBiensView.as_view(), name='agent_biens'),
    path('agents/<int:pk>/avis/', AgentAvisView.as_view(), name='agent_avis'),
    path('agents/<int:pk>/avis/ajouter/', LaisserAvisAgentView.as_view(), name='laisser_avis_agent'),
]
