# Generated by Django 6.0.3 on 2026-07-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0008_bien_est_suspect_bien_raisons_suspicion_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='biens.bien'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Système'), ('saved_search', 'Recherche sauvegardée'), ('price_drop', 'Baisse de prix')], default='system', max_length=20),
        ),
    ]
