# Generated by Django 6.0.3 on 2026-07-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_bien_notification_dedup_key_and_more'),
        ('reservations', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'Système'), ('saved_search', 'Recherche sauvegardée'), ('price_drop', 'Baisse de prix'), ('message', 'Nouveau message'), ('reservation', 'Réservation'), ('document', 'Vérification de document')], default='system', max_length=20),
        ),
    ]
